<a href="https://colab.research.google.com/github/LuanLindolfo/tcc/blob/main/tcc_censo_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Censo 2022 - 1º de agosto de 2022 a 07 de julho de 2023
Castanhal - https://censo2022.ibge.gov.br/panorama/mapas.html?tema=populacao&recorte=N6

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip -q install plotly #gráficos e visualização de dados
!pip -q install yellowbrick #para ferramenta de modelos de aprendizagem automática de diagnóstico de modelos
!pip install numpy #computação numérica

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
from google.colab import drive#carregando a base de dados pro ambiente do collab
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Demografia

## População Total e Distribuição

In [ ]:
populacao_residente = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - População residente - Municípios.xlsx').query("Municípios == 'Castanhal'")
populacao_residente

     Municípios  Código municipal  UF  pessoas
1170  Castanhal           1502400  PA   192256

In [ ]:
densidade_populacional = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Densidade demográfica - Municípios.xlsx').query("Municípios == 'Castanhal'")
densidade_populacional

     Municípios  Código municipal  UF habitantes por km²
1170  Castanhal           1502400  PA             186,78

não consegui acessar a distribuição da população por bairros ou setores censitários

In [ ]:
#Vendo se pode ser interessante
populacao_urbana = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - População urbana - Municípios.xlsx').query("Municípios == 'Castanhal'")
populacao_urbana

     Municípios  Código municipal  UF      %
1170  Castanhal           1502400  PA  92,52

In [ ]:
taxa_crescimento = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Taxa de crescimento anual da população - Municípios.xlsx').query("Municípios == 'Castanhal'")
taxa_crescimento

     Municípios  Código municipal  UF     %
1170  Castanhal           1502400  PA  0,88

## Estrutura Etária e de Gênero

In [ ]:
piramide_etaria = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Pirâmide etária - Castanhal (PA).xlsx')
piramide_etaria

,Grupo de idade,População feminina(pessoas),População masculina(pessoas),Município,Sigla UF,Código do Município,codMun
0,100 anos ou mais,21,8,Total,Castanhal,PA,1502400
1,95 a 99 anos,70,29,Total,Castanhal,PA,1502400
2,90 a 94 anos,194,111,Total,Castanhal,PA,1502400
3,85 a 89 anos,429,294,Total,Castanhal,PA,1502400
4,80 a 84 anos,868,615,Total,Castanhal,PA,1502400
5,75 a 79 anos,1346,1017,Total,Castanhal,PA,1502400
6,70 a 74 anos,2040,1640,Total,Castanhal,PA,1502400
7,65 a 69 anos,2911,2434,Total,Castanhal,PA,1502400
8,60 a 64 anos,3812,3177,Total,Castanhal,PA,1502400
9,55 a 59 anos,4599,4072,Total,Castanhal,PA,1502400
10,50 a 54 anos,5631,5224,Total,Castanhal,PA,1502400
11,45 a 49 anos,6590,5917,Total,Castanhal,PA,1502400
12,40 a 44 anos,8094,7303,Total,Castanhal,PA,1502400
13,35 a 39 anos,8768,7666,Total,Castanhal,PA,1502400
14,30 a 34 anos,8517,7600,Total,Castanhal,PA,1502400
15,25 a 29 anos,8474,7628,Total,Castanhal,PA,1502400
16,20 a 24 anos,8650,8275,Total,Castanhal,PA,1502400
17,15 a 19 anos,8141,7928,Total,Castanhal,PA,1502400
18,10 a 14 anos,7229,7622,Total,Castanhal,PA,1502400
19,5 a 9 anos,6876,7136,Total,Castanhal,PA,1502400
20,0 a 4 anos,6490,6810,Total,Castanhal,PA,1502400

In [ ]:
#ambos no mesmo dataframe
indice_envelhecimento_razao_sexo = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Razão de sexo e índice de envelhecimento - Castanhal (PA).xlsx')
indice_envelhecimento_razao_sexo

,homens para cada 100 mulheres,pessoas com 60+ anos para cada 100 com até 14 anos,Município,Sigla UF,Código do Município
0,"92,74","49,84",Castanhal,PA,1502400

In [ ]:
#separando o indice envelhecimento
indice_envelhecimento = indice_envelhecimento_razao_sexo[['pessoas com 60+ anos para cada 100 com até 14 anos', 'Município', 'Sigla UF', 'Código do Município']]
indice_envelhecimento

,pessoas com 60+ anos para cada 100 com até 14 anos,Município,Sigla UF,Código do Município
0,"49,84",Castanhal,PA,1502400

In [ ]:
#separando o razao sexo
razao_sexo = indice_envelhecimento_razao_sexo[['homens para cada 100 mulheres', 'Município', 'Sigla UF', 'Código do Município']]
razao_sexo

  homens para cada 100 mulheres   Município Sigla UF  Código do Município
0                         92,74  Castanhal        PA              1502400

# Domicílios

## Tipos de Domicílio

In [ ]:
taxa_domicilio = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Quantidade de domicílios - Municípios.xlsx').query("Municípios == 'Castanhal'")
taxa_domicilio

     Municípios  Código municipal  UF  domicílios
1170  Castanhal           1502400  PA       80009

In [ ]:
distribuicao_domicilios = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Tipos de domicílio - Castanhal (PA).xlsx')
distribuicao_domicilios

,Casa,Casa de vila ou condominio,Apartamento,Cortiço,Estrutura degradada ou inacabada,Maloca,Município,Sigla UF,Código do Município
0,54981,5126,3609,59,8,-,Castanhal,PA,1502400

## Condições de Moradia

In [ ]:
#Número médio de moradores por domicílio.
numero_moradores = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Domicilios por numero de moradores - Castanhal (PA).xlsx')
numero_moradores

,Número de moradores,Domicílios,Porcentagem,Município,Sigla UF,Código do Município
0,1,9284,"14,54",Castanhal,PA,1502400
1,2,15858,"24,83",Castanhal,PA,1502400
2,3,16931,"26,51",Castanhal,PA,1502400
3,4,13433,"21,03",Castanhal,PA,1502400
4,5,5457,"8,54",Castanhal,PA,1502400
5,6 ou mais,2907,"4,55",Castanhal,PA,1502400

In [ ]:
#achei interessante - Domicílios Particulares Permanentes Ocupados
media_moradores = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Média de moradores por domicílio - Castanhal (PA).xlsx')
media_moradores

   Domicílios Média de moradores   Município Sigla UF  Código do Município
0       63783               3,01  Castanhal        PA              1502400

In [ ]:
#achei interessante - por particularidade
moradores_por_idade= pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Média de moradores em domicílios por grupo de idade do responsável - Castanhal (PA).xlsx')
moradores_por_idade

,Grupo de idade do responsável,Média de moradores,Município,Sigla UF,Código do Município
0,Até 17 anos,"3,43",Castanhal,PA,1502400
1,18 a 24 anos,"2,74",Castanhal,PA,1502400
2,25 a 39 anos,"3,18",Castanhal,PA,1502400
3,40 a 59 anos,"3,09",Castanhal,PA,1502400
4,60 anos ou mais,"2,64",Castanhal,PA,1502400

In [ ]:
caracteristicas_domicilio = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Características dos domicílios - Castanhal (PA).xlsx')
caracteristicas_domicilio

,Característica do domicílio,Total,Porcentagem,Município,Sigla UF,Código do Município
0,Conexão à rede de esgoto,10962,"17,19",Castanhal,PA,1502400
1,Abastecimento de água pela rede geral,27565,"43,22",Castanhal,PA,1502400
2,Banheiro de uso exclusivo,62782,"98,43",Castanhal,PA,1502400
3,Coleta de lixo,60413,"94,72",Castanhal,PA,1502400

In [ ]:
material_paredes = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Tipo de material das paredes externas - Castanhal (PA).xlsx')
material_paredes

,Alvenaria ou taipa c/ revestimento,Alvenaria sem revestimento,Taipa sem revestimento,Madeira para construção,Madeira reaproveitada,Outro material,Sem parede,Município,Sigla UF,Código do Município
0,54379,5125,483,667,155,3008,0,Castanhal,PA,1502400

In [ ]:
#não achei o de energia

## Posse e Condição de Ocupação

In [ ]:
condicoes_ocupacao = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Condições de ocupação - Castanhal (PA).xlsx')
condicoes_ocupacao

,Condição,Domicílios,Porcentagem,Município,Sigla UF,Código do Município
0,"Próprio, já pago",40030,"62,73",Castanhal,PA,1502400
1,"Próprio, pagando",7877,"12,34",Castanhal,PA,1502400
2,Alugado,11685,"18,31",Castanhal,PA,1502400
3,Cedido ou emprestado,3175,"4,98",Castanhal,PA,1502400
4,Outro,1051,"1,65",Castanhal,PA,1502400

# Educação

## Nível de Escolaridade

In [ ]:
nivel_instrucao = pd.read_excel ('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Nível de instrução - Castanhal (PA).xlsx')
nivel_instrucao

,Sem instrução e fundamental incompleto,Fundamental completo e médio incompleto,Médio completo e superior incompleto,Superior completo,Município,Sigla UF,Código do Município
0,42679,26909,53458,17556,Castanhal,PA,1502400

In [ ]:
alfabetizacao = pd.read_excel ('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Alfabetização - Castanhal (PA).xlsx')
alfabetizacao

,Situação,População(pessoas),Percentual,Município,Sigla UF,Código do Município
0,Alfabetizados,141275,"94,12",Castanhal,PA,1502400
1,Não alfabetizados,8818,"5,88",Castanhal,PA,1502400

### Dados tirado por tabelas específicas do estudo do censo via [SIDRA](https://sidra.ibge.gov.br/home/pimpfbr/brasil) (pertence ao IBGE)

In [ ]:
analise_escolaridade_mulheres = pd.read_excel('/content/drive/MyDrive/censo_castanhal/analise_escolaridade_mulheres.xlsx')
analise_escolaridade_mulheres

,"Tabela 10061 - Pessoas de 18 anos ou mais de idade, por nível de instrução, segundo os grupos de idade, o sexo e a cor ou raça",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Variável - Pessoas de 18 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Município,Sexo,Cor ou raça,Ano x Nível de instrução x Grupo de idade,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Total,Sem instrução e fundamental incompleto,Fundamental completo e médio incompleto,Médio completo e superior incompleto,Superior completo
4,NaN,NaN,NaN,Total,Total,Total,Total,Total
5,Castanhal (PA),Mulheres,Total,73918,20224,13134,29631,10930
6,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
analise_escolaridade_homens = pd.read_excel('/content/drive/MyDrive/censo_castanhal/analise_escolaridade_homens.xlsx')
analise_escolaridade_homens

,"Tabela 10061 - Pessoas de 18 anos ou mais de idade, por nível de instrução, segundo os grupos de idade, o sexo e a cor ou raça",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Variável - Pessoas de 18 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Município,Sexo,Cor ou raça,Ano x Nível de instrução x Grupo de idade,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Total,Sem instrução e fundamental incompleto,Fundamental completo e médio incompleto,Médio completo e superior incompleto,Superior completo
4,NaN,NaN,NaN,Total,Total,Total,Total,Total
5,Castanhal (PA),Homens,Total,66684,22455,13775,23828,6626
6,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
analise_escolaridade_mulheres_percentual = pd.read_excel('/content/drive/MyDrive/censo_castanhal/analise_escolaridade_mulheres_percetual.xlsx')
analise_escolaridade_mulheres_percentual

,"Tabela 10061 - Pessoas de 18 anos ou mais de idade, por nível de instrução, segundo os grupos de idade, o sexo e a cor ou raça",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Variável - Pessoas de 18 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Município,Sexo,Cor ou raça,Ano x Nível de instrução x Grupo de idade,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Total,Sem instrução e fundamental incompleto,Fundamental completo e médio incompleto,Médio completo e superior incompleto,Superior completo
4,NaN,NaN,NaN,Total,Total,Total,Total,Total
5,Castanhal (PA),Mulheres,Total,52.57251,14.38386,9.34126,21.07438,7.77372
6,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
analise_escolaridade_homens_percentual = pd.read_excel('/content/drive/MyDrive/censo_castanhal/analise_escolaridade_homens_percetual.xlsx')
analise_escolaridade_homens_percentual

,"Tabela 10061 - Pessoas de 18 anos ou mais de idade, por nível de instrução, segundo os grupos de idade, o sexo e a cor ou raça",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Variável - Pessoas de 18 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Município,Sexo,Cor ou raça,Ano x Nível de instrução x Grupo de idade,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Total,Sem instrução e fundamental incompleto,Fundamental completo e médio incompleto,Médio completo e superior incompleto,Superior completo
4,NaN,NaN,NaN,Total,Total,Total,Total,Total
5,Castanhal (PA),Homens,Total,47.42749,15.97061,9.79716,16.94713,4.71259
6,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Frequência escolar

In [ ]:
frequencia_escolar_idade = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Taxa bruta de frequência escolar, por grupo de idade - Castanhal (PA).xlsx')
frequencia_escolar_idade

,Grupo de idade,Taxa bruta de frequência escolar (%),Município,Sigla UF,Código do Município
0,0 a 3 anos,"10,19",Castanhal,PA,1502400
1,4 e 5 anos,"81,78",Castanhal,PA,1502400
2,6 a 14 anos,"98,45",Castanhal,PA,1502400
3,15 a 17 anos,"85,83",Castanhal,PA,1502400
4,18 a 24 anos,"33,66",Castanhal,PA,1502400
5,25 anos ou mais,"7,09",Castanhal,PA,1502400

# Trabalho e Renda

## População Economicamente Ativa (PEA)

In [ ]:
taxa_atividade = pd.read_excel('/content/drive/MyDrive/censo_castanhal/taxa_atividade.xlsx')
taxa_atividade

,"Tabela 1572 - Pessoas de 10 anos ou mais de idade, por idade e condição de atividade e de ocupação na semana de referência - Resultados Gerais da Amostra",Unnamed: 1,Unnamed: 2
0,Variável - Pessoas de 10 anos ou mais de idade...,NaN,NaN
1,Município,Condição de atividade e condição de ocupação,Ano x Idade
2,NaN,NaN,2010
3,NaN,NaN,Total
4,Castanhal (PA),Total,141833
5,NaN,Economicamente ativas,75129
6,NaN,Economicamente ativas - ocupadas,67766
7,NaN,Economicamente ativas - desocupadas,7363
8,NaN,Não economicamente ativas,66705
9,Fonte: IBGE - Censo Demográfico,NaN,NaN

In [ ]:
taxa_atividade_percentual = pd.read_excel('/content/drive/MyDrive/censo_castanhal/taxa_atividade_percentual.xlsx')
taxa_atividade_percentual

,"Tabela 1575 - Pessoas de 10 anos ou mais de idade, ocupadas na semana de referência, por seção de atividade do trabalho principal - Resultados Gerais da Amostra",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Variável - Pessoas de 10 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Município,Ano x Seção de atividade do trabalho principal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Total,"Agricultura, pecuária, produção florestal, pes...",Indústrias extrativas,Indústrias de transformação,Eletricidade e gás,"Água, esgoto, atividades de gestão de resíduos...",Construção,Comércio; reparação de veículos automotores e ...,"Transporte, armazenagem e correio",...,"Atividades profissionais, científicas e técnicas",Atividades administrativas e serviços compleme...,"Administração pública, defesa e seguridade social",Educação,Saúde humana e serviços sociais,"Artes, cultura, esporte e recreação",Outras atividades de serviços,Serviços domésticos,Organismos internacionais e outras instituiçõe...,Atividades mal especificadas
4,Castanhal (PA),67766,5959,124,7646,285,261,5778,17502,2998,...,948,1681,3964,3396,1593,748,1945,4702,-,4996
5,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
profissao = pd.read_excel('/content/drive/MyDrive/censo_castanhal/profissões.xlsx')
profissao

,"Tabela 1573 - Pessoas de 10 anos ou mais de idade, ocupadas na semana de referência, por grandes grupos de ocupação no trabalho principal - Resultados Gerais da Amostra",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Variável - Pessoas de 10 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Município,Ano x Grandes grupos de ocupação no trabalho p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Total,Diretores e gerentes,Profissionais das ciências e intelectuais,Técnicos e profissionais de nível médio,Trabalhadores de apoio administrativo,"Trabalhadores dos serviços, vendedores dos com...","Trabalhadores qualificados da agropecuária, fl...","Trabalhadores qualificados, operários e artesã...",Operadores de instalações e máquinas e montadores,Ocupações elementares,"Membros das forças armadas, policiais, bombeir...",Ocupações mal definidas
4,Castanhal (PA),67766,1927,4675,3866,4605,14628,3608,9141,6167,12878,516,5756
5,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Renda

In [ ]:
rendimento_domiciliar_per_capita = pd.read_excel('/content/drive/MyDrive/censo_castanhal/Censo 2022 - Rendimento domiciliar mensal per capita - Castanhal (PA).xlsx')
rendimento_domiciliar_per_capita

    Ano Rendimento (R$)   Município Sigla UF  Código do Município
0  2022        1.055,05  Castanhal        PA              1502400

In [ ]:
#Distribuição de renda por gênero, etnia, idade
distribuicao_renda = pd.read_excel('/content/drive/MyDrive/censo_castanhal/distribuição de renda.xlsx')
distribuicao_renda

,"Tabela 10381 - Pessoas de 10 anos ou mais ocupadas na semana de referência e sua distribuição, por cor ou raça, segundo as classes de rendimento de todos os trabalhos",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Variável - Pessoas de 10 anos ou mais de idade...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Município,Classes de rendimento nominal mensal de todos ...,Ano x Cor ou raça,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Total,Branca,Preta,Amarela,Parda,Indígena
4,Castanhal (PA),Total,75394,17097,7703,328,50181,85
5,NaN,Até 1/4 de salário mínimo,3368,462,375,11,2520,-
6,NaN,Mais de 1/4 a 1/2 salário mínimo,6848,1279,723,7,4840,-
7,NaN,Mais de 1/2 a 1 salário mínimo,26202,5303,2758,88,18025,28
8,NaN,Mais de 1 a 2 salários mínimos,22647,5053,2542,68,14927,57
9,NaN,Mais de 2 a 3 salários mínimos,7647,2234,725,53,4636,-
10,NaN,Mais de 3 a 5 salários mínimos,4775,1309,299,33,3135,-
11,NaN,Mais de 5 a 10 salários mínimos,2146,855,154,59,1078,-
12,NaN,Mais de 10 a 15 salários mínimos,340,144,35,-,161,-
13,NaN,Mais de 15 a 20 salários mínimos,299,131,14,-,154,-
14,NaN,Mais de 20 salários mínimos,243,137,26,-,81,-
15,NaN,Sem rendimento,879,190,54,10,624,-
16,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN

indice gini ta defasado

não enconterei Rendimento médio mensal das pessoas de 14 anos ou mais de idade, por nível de instrução no sidra